export enum CC_EVENTS {
    TIME_SLOW = "time_slow",
    TIME_RESUME = "time_resume",
    SHOW_PLACEMENT_GRID = "show_placement_grid",
    HIDE_PLACEMENT_GRID = "hide_placement_grid",
    PLACE_BLOCK = "place_block",
    PLAYER_ENTERED_LEVEL_END = "PlayerEnteredLevelEnd",
    LEVEL_START = "level_start",
    LEVEL_END = "level_end",
    PLAYER_HIT_FLOATING_BLOCK_CARD = "PlayerHitFloatingBlockCard",
    PLAYER_HIT_SPRING_BLOCK_CARD = "PlayerHitSpringBlockCard",
    PLAYER_HIT_CIRCULAR_ROCK_CARD = "PlayerHitCircularRockCard",
    SPRING_TRIGGERED = "spring_triggered",
    CARD_CLICKED = "card_clicked",
    SPRING_TRIGGERED_TOP = "spring_triggered_top",
    SPRING_TRIGGERED_DOWN = "spring_triggered_down",
    SPRING_TRIGGERED_LEFT = "spring_triggered_left",
    SPRING_TRIGGERED_RIGHT = "spring_triggered_right",
    PLAYER_JUMP = "player_jump",
    PLAYER_MOVE = "player_move"
}